### ISSUE TITLE
pyakm (or Arch Linux Kernel Manager) The program no longer starts

### ISSUE THREAD

**Issue by Xeers** [pssncp142/pyakm#1]
pyakm (or Arch Linux Kernel Manager) The program no longer starts, it needs to be updated.

sudo systemctl restart pyakm-system

Job for pyakm-system.service failed because the control process exited with error code.
See "systemctl status pyakm-system.service" and "journalctl -xe" for details.

$ systemctl status pyakm-system.service
● pyakm-system.service - Pyakm System Session
Loaded: loaded (/usr/lib/systemd/system/pyakm-system.service; static; vendor preset: disabled)
Active: failed (Result: exit-code) since Wed 2018-08-08 11:26:33 CEST; 52s ago
Process: 9593 ExecStart=/usr/bin/pyakm-system-daemon (code=exited, status=1/FAILURE)
Main PID: 9593 (code=exited, status=1/FAILURE)

ago 08 11:26:33 Velkerk-pc systemd[1]: Starting Pyakm System Session...
ago 08 11:26:33 Velkerk-pc pyakm-system-daemon[9593]: Traceback (most recent call last):
ago 08 11:26:33 Velkerk-pc pyakm-system-daemon[9593]: File "/usr/bin/pyakm-system-daemon", line 26, in <module>
ago 08 11:26:33 Velkerk-pc pyakm-system-daemon[9593]: from pyakm.dbus import Server
ago 08 11:26:33 Velkerk-pc pyakm-system-daemon[9593]: ModuleNotFoundError: No module named 'pyakm'
ago 08 11:26:33 Velkerk-pc systemd[1]: pyakm-system.service: Main process exited, code=exited, status=1/FAILURE
ago 08 11:26:33 Velkerk-pc systemd[1]: pyakm-system.service: Failed with result 'exit-code'.
ago 08 11:26:33 Velkerk-pc systemd[1]: Failed to start Pyakm System Session.

$ journalctl -xe
ago 08 11:28:26 Velkerk-pc deepin-fix.sh[702]: none
ago 08 11:28:26 Velkerk-pc deepin-fix.sh[702]: none
ago 08 11:28:26 Velkerk-pc deepin-fix.sh[702]: none
....

**Comment by karasu** [comment]
Probably it's because of the new Python 3.7 release. @pssncp142  I'd guess that a simple rebuild of the package would do the trick.

**Comment by ydallilar** [comment]
Thanks @Xeers for reporting and @karasu for the tip. I will have a look some time this week.

**Comment by ydallilar** [comment]
Yeah so, I just bumped the release number of the package in aur. It works as it should.
